---
- name: install java and net-tools
  hosts: nexus_centos
  become: yes
  tasks:
    - name: update the system
      yum: update_cache=yes
    - name: install the java jdk
      yum: name=java-1.8.0-openjdk-devel

- name: download & unpack the nexus installer
  hosts: nexus_centos
  become: yes
  tasks:
    - name: check if nexus folder already exists
          stat:
            path: /opt/nexus
          register: stat_result
    #    - debug: msg={{stat_result.stat.exists}}
    - name: download the nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
#    - debug: msg={{download_result}}
    - name: un-tar nexus installation file
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: find the nexus
      find:
        paths: /opt
        patterns: "nexus-*"
        file_type: directory
      register: find_result
#    - debug:
#        msg: "{{find_result}}"
    - name: rename the nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: create nexus user and change the owner
  hosts: nexus_centos
  become: yes
  tasks:
    - name: Ensure group nexus exists
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: nexus folder owner
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: sonatype-work folder owner
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: nexus with nexus user
  hosts: nexus_centos
  become: yes
  tasks:
    - name: set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"