---
- name: install java and net-tools
  hosts: nexus_centos
  become: yes
  tasks:
    - name: update the system
      yum: update_cache=yes
    - name: install the java jdk
      yum: name=java-1.8.0-openjdk-devel

- name: download & unpack the nexus installer
  hosts: nexus_centos
  become: yes
  tasks:
    - name: download the nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
#    - debug: msg={{download_result}}

    - name: untar necus installation file
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
#    - name: rename the nexus folder
#      shell:

    - name: find the nexus
      find:
        paths: /opt
        patherns: ["nexus-*"]
#        file_type: directory
#      register: find_result
#    - debug: msg={{find_result}}
