---
- name: install java and net-tools
  hosts: nexus_centos
  become: yes
  tasks:
    - name: update the system
      yum: update_cache=yes
    - name: install the java jdk
      yum: name=java-1.8.0-openjdk-devel

- name: download & unpack the nexus installer
  hosts: nexus_centos
  become: yes
  tasks:
    - name: download the nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
#    - name: untar necus installation file
#      unarchive:
#        src: /opt/nexus-3.42.0-01-unix.tar.gz
#        dest: /opt/
#        remote_src: yes