    - name: copy docker compose
      copy:
        src: /home/centos/ansible-try/ansible/docker-compose.yml
        dest: /home/sandy/docker-compose.yml

    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: sandeepcomsole
        password: "{{password}}"

    - name: start container form docker compose
      docker_compose:
        project_src: /home/sandy
        #            state: present # docker-compose up