---
- name: deploy app in new namespace
  hosts: localhost
  tasks:
    - name: create a k8s namespace
      k8s:
        name: ansible
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/.kube/config
    - name: Deploy nginx app
      k8s:
        src: /root/ansible-try/EKS/nginx.yml
        state: present
        kubeconfig: /root/.kube/config
        namespace: ansible
