---
    - name: wait for ssh connection
      hosts: all
      gather_facts: False
      tasks:
        - name: Ensure ssh connection
          wait_for:
            port: 22
            delay: 10
            timeout: 100
            search_regex: OpenSSH
            host: '{{(ansible_ssh_host|default(ansible_host))|default(inventory_hostname)}}'
          vars:
            ansible_connection: local
            ansible_python_interpreter: /usr/bin/python



    - name: Install python && docker
      hosts: all
      gather_facts: False
      become: yes
      tasks:
        - name: Add Docker repo
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docer-ce.repo

        - name: Install python3, docker and docker compose
          vars:
            ansible_python_interpreter: /usr/bin/python
          yum:
            name:
              - yum-utils
              - python3
              - docker-ce
            update_cache: yes
            state: present
        - name: Install docker python module
          pip:
            name:
              - docker
              - docker-compose
        - name: Install docker compose
          get_url:
            url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
            dest: /usr/local/bin/docker-compose
            mode: +x
        - name: Ensure docker is running
          systemd:
            name: docker
            state: started

    - name: create new linux user
      hosts: all
      become: yes
      roles:
        - Create_user

    - name: start docker compose
      hosts: all
      become: yes
      become_user: sandy
      vars_files:
        - install-vars
      roles:
        - start_containers

