---
- name: install node & npm
  hosts: centos
  become: yes
  tasks:
    - name: update yum repo & cache
      yum: update_cache=yes
    - name: installation node & npm
      yum:
        pkg:
          - nodejs
          - npm

- name: create new user for node app
  hosts: centos
  become: yes
  tasks:
    - name: create the user
      user:
        name: sand
        comment: sand admin
#        group: centos
      register: user_creation_result
    - debug: msg={{user_creation_result.uid}}


- name: Deploy nodejs app
  hosts: centos
  become: True
  become_user: sand
  vars:
#    - app-file-location: /home/centos/simple-nodejs-master/nodejs-app-1.0.0.tgz
    - location: /home/centos
    - version: 1.0.0
    - destination: /home/sand
  tasks:
#    - name: copy nodejs folder tp a server
#      copy:
#        src: /home/centos/simple-nodejs-master/nodejs-app-1.0.0.tgz
#        dest: /home/centos/app-1.0.0.tgz

    - name: create the package
      file:
        name: package
        path: /home/sand/
        state: directory

#    - name: unpack the nodejs tar file
#      unarchive:
#        src: /home/centos/app-1.0.0.tgz
#        dest: /home/centos/package
#        remote_src: yes

    - name: unpack the nodejs tar file
      unarchive:
#        src: /home/centos/simple-nodejs-master/nodejs-app-{{version}}.tgz
#        src: "{{app-file-location}}"
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
      register: user_creation_result
    - debug: msg={{user_creation_result.uid}}

    - name: install dependencies
      npm:
        path: "{{destination}}/package"

    - name: start the application
      command:
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0

    - name: ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
